/**
 * Add anchor link functionality to headings
 * Allows users to click headings to copy the anchor link
 */
export function initHeadingAnchors(): void {
	const headings = document.querySelectorAll('.prose h2, .prose h3, .prose h4, .prose h5, .prose h6');

	headings.forEach(heading => {
		// Get the id from the heading (generated by Astro)
		const id = heading.id;
		if (!id) return;

		// Add click handler
		heading.addEventListener('click', async () => {
			const anchorLink = `${window.location.href.split('#')[0]}#${id}`;
			try {
				await navigator.clipboard.writeText(anchorLink);

				const status = document.querySelector<HTMLElement>('[data-assist-status]');
				if (status) status.textContent = 'Heading link copied';
			} catch (err) {
				console.error('Failed to copy anchor link:', err);

			}
		});

		// Add accessible tooltip on hover
		heading.setAttribute('title', `Click to copy anchor link to: ${id}`);
	});
}
