/**
 * Add anchor link functionality to headings
 * Allows users to click headings to copy the anchor link with toast notification
 */
export async function initHeadingAnchors() {
	// Dynamically import sonner's toast function
	let toastFn: any = null;
	try {
		const sonner = await import('sonner');
		toastFn = sonner.toast;
	} catch (err) {
		console.warn('Sonner not available for toast notifications');
	}

	const headings = document.querySelectorAll('.prose h2, .prose h3, .prose h4, .prose h5, .prose h6');

	headings.forEach(heading => {
		// Get the id from the heading (generated by Astro)
		const id = heading.id;
		if (!id) return;

		// Add click handler
		heading.addEventListener('click', async () => {
			const anchorLink = `${window.location.href}#${id}`;
			try {
				await navigator.clipboard.writeText(anchorLink);

				// Show toast notification if sonner is available
				if (toastFn) {
					toastFn.success('Anchor link copied!', {
						description: `Link: #${id}`,
						duration: 2000,
					});
				} else {
					// Fallback visual feedback if sonner is not available
					const originalColor = heading.style.color;
					heading.style.color = 'var(--accent)';
					setTimeout(() => {
						heading.style.color = originalColor;
					}, 200);
				}
			} catch (err) {
				console.error('Failed to copy anchor link:', err);
				if (toastFn) {
					toastFn.error('Failed to copy link', {
						description: 'Please try again',
						duration: 2000,
					});
				}
			}
		});

		// Add accessible tooltip on hover
		heading.setAttribute('title', `Click to copy anchor link to: ${id}`);
	});
}

// Run when DOM is ready
if (document.readyState === 'loading') {
	document.addEventListener('DOMContentLoaded', initHeadingAnchors);
} else {
	initHeadingAnchors();
}
